name: build artifacts
on: [push, pull_request]
jobs:
  build-repl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: Install dependencies
        run: go mod download
      - name: Build Repl
        working-directory: cmd/bundler-repl
        run: go build
  build-server:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-go@v3
       with:
         go-version: 1.15
     - name: Install dependencies
       run: go mod download
     - name: Build Server
       working-directory: cmd/bundler-server
       run: go build
