name: run test coverage
on: [push, pull_request]
jobs:
  run_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: Go Get
        run: go get .
      - name: Go Build
        run: go build -v ./...
      - name: Generate Coverage
        run: go test -cover -v ./...
