name: run test coverage
on: [push, pull_request]
jobs:
  run_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        run: go mod download
      - name: Generate Coverage
        run: go test -cover -v ./...
